//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gopnik_Hotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boeking
    {
        public int BoekingId { get; set; }
        public System.DateTime Datum { get; set; }
        public int IdKamer { get; set; }
        public int IdKlant { get; set; }
    
        public virtual Kamer Kamer { get; set; }
        public virtual Klant Klant { get; set; }
    }
}
