//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gopnik_Hotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kamer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kamer()
        {
            this.Boekings = new HashSet<Boeking>();
        }
    
        public int KamerId { get; set; }
        public string Naam { get; set; }
        public int Grootte { get; set; }
        public decimal Prijs { get; set; }
        public string Afbeelding { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boeking> Boekings { get; set; }
    }
}
